apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualification
  labels:
    app: qualification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualification
  template:
    metadata:
      labels:
        app: qualification
    spec:
      containers:
        - name: qualification
          image: 496278789073.dkr.ecr.ap-northeast-1.amazonaws.com/recruit-qualification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PASSWD
              valueFrom:
                secretKeyRef:
                  name: my-password
                  key: password
            - name: CONFIGDATA
              valueFrom:
                configMapKeyRef:
                  name: hotelcm
                  key: text1
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5